apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: stock-app-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rudra273/stock-frontend:test4
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://backend:8000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: stock-app-ci
spec:
  ports:
    - port: 3000
  selector:
    app: frontend
