apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: stock-app-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
        - name: metrics-collector
          image: rudra273/metrics-collector:latest
          ports:
            - containerPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
  namespace: stock-app-ci
spec:
  ports:
    - port: 7878
  selector:
    app: metrics-collector
