apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: stock-app-ci
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'backend'
        static_configs:
          - targets: ['backend:8000']
      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend:3000']
      - job_name: 'metrics_collector'
        static_configs:
          - targets: ['metrics-collector:7878']
